# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62467e3931512c854f9b5e545316feb6"
application_url = "https://d22efc70mwp7f4.cloudfront.net/"
embedded = true
name = "demo-lambda-2"
handle = "demo-lambda-2"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://d22efc70mwp7f4.cloudfront.net/api/auth" ]

[pos]
embedded = false
